# Generated by Django 5.0.1 on 2025-10-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("channel_type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "discord_channels",
            },
        ),
        migrations.CreateModel(
            name="DiscordServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "discord_servers",
            },
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(max_length=100)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("discriminator", models.CharField(blank=True, max_length=10)),
                ("avatar_url", models.URLField(blank=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "discord_users",
            },
        ),
        migrations.CreateModel(
            name="DiscordMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField(unique=True)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("edited_timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("has_attachments", models.BooleanField(default=False)),
                ("attachment_count", models.PositiveIntegerField(default=0)),
                ("has_embeds", models.BooleanField(default=False)),
                ("embed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot.discordchannel",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot.discorduser",
                    ),
                ),
            ],
            options={
                "db_table": "discord_messages",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="discordchannel",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="bot.discordserver",
            ),
        ),
        migrations.CreateModel(
            name="DiscordReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji_name", models.CharField(max_length=100)),
                ("emoji_id", models.BigIntegerField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="bot.discordmessage",
                    ),
                ),
            ],
            options={
                "db_table": "discord_reactions",
                "unique_together": {("message", "emoji_name", "emoji_id")},
            },
        ),
        migrations.AddIndex(
            model_name="discordmessage",
            index=models.Index(
                fields=["timestamp"], name="discord_mes_timesta_0642b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordmessage",
            index=models.Index(
                fields=["channel", "timestamp"], name="discord_mes_channel_3224d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordmessage",
            index=models.Index(
                fields=["author", "timestamp"], name="discord_mes_author__ba4d18_idx"
            ),
        ),
    ]
